name: Continuos Integration API

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: api

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Test
      run: |
        make test
    - name: Typecheck
      run: |
        make typecheck
    - name: Lint
      run: |
        make lint
