name: Continuos Integration Client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: client

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install
      run: |
        yarn install
    - name: Build
      run: |
        yarn build
    - name: Test
      run: |
        yarn test
